### ISSUE TITLE
Need Delay and throttle mode (when we hover too much tooltips)

### ISSUE THREAD

**Issue by RALMAZ** [yujinpan/v-title#1]

**Comment by yujinpan** [comment]
Hi, you can add the new modify `delay` to show delay.

Online example: https://yujinpan.github.io/v-title/
Options: https://github.com/yujinpan/v-title#complete-example

**Comment by yujinpan** [comment]
Remember to update version.

**Comment by RALMAZ** [comment]
Thank you so much)
