### ISSUE TITLE
Need more Configuration options（such as tooltip-class，max-width）

### ISSUE THREAD

**Issue by Dellear** [yujinpan/v-title#2]
The plug-in is very easy to use, but the custom function is a little insufficient. When I use `title-placement="bottom-start"` , it often goes beyond the window at the edge, and I can't control it

**Comment by yujinpan** [comment]
Hey, how it goes beyond？

**Comment by Dellear** [comment]
> Hey, how it goes beyond？

 just like this
![image](https://user-images.githubusercontent.com/22325851/92998014-eadd2280-f549-11ea-9742-e7ba83eba242.png)

**Comment by yujinpan** [comment]
New options have been added in the new version.

Such as: `title-max-width`, `title-class-name`.

Thanks for waiting.

See more: https://github.com/yujinpan/v-title#attributes
